### ISSUE TITLE
excepiton in /api/Product PUT (swagger)

### ISSUE THREAD

**Issue by valpetruk** [yhurynovich/MembersipCashier#4]
Possible cause: 
in Product_Location_Price_Contract, set method for Location property - value object is null so value.CopyTo(x) throws Object reference not set to an instance of an object. -> SessionGlobal.CurrentLocation is null.
[JsonIgnore]
        public ILocation Location
        {
            get { return (_location as ILocation); }
            set { var x = new LocationImplementor(); value.CopyTo(x); _location = x; }
        }

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Object reference not set to an instance of an object.",
  "ExceptionType": "System.NullReferenceException",
  "StackTrace": "   at MembershipCashierUnified.Extentions_CopyTo.CopyTo(IHasLocationId from, IHasLocationId to, Boolean allowDefaultValues) in D:\\Development\\Git\\MembersipCashier\\MembersipCashier\\MembershipCashierUnified\\Extentions_CopyTo.cs:line 106\r\n   at MembershipCashierUnified.Extentions_CopyTo.CopyTo(ILocation from, ILocation to, Boolean allowDefaultValues) in D:\\Development\\Git\\MembersipCashier\\MembersipCashier\\MembershipCashierUnified\\Extentions_CopyTo.cs:line 111\r\n   at MembershipCashierDL.MixedContracts.Product_Location_Price_Contract.set_Location(ILocation value) in D:\\Development\\Git\\MembersipCashier\\MembersipCashier\\MembershipCashierDL\\MixedContracts\\Product_Location_Price_Contract.cs:line 19\r\n   at MembershipCashierW.Controllers.ProductController.<>c.<Put>b__4_1(NewProductRequest d) in D:\\Development\\Git\\MembersipCashier\\MembersipCashier\\MembershipCashierW\\Controllers\\ProductController.cs:line 113\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at MembershipCashierW.Controllers.ProductController.<>c__DisplayClass4_0.<Put>b__0() in D:\\Development\\Git\\MembersipCashier\\MembersipCashier\\MembershipCashierW\\Controllers\\ProductController.cs:line 113\r\n   at MembershipCashierW.Controllers.ControllerBase.WebApiControllerBase.Execute[T](Func`1 action) in D:\\Development\\Git\\MembersipCashier\\MembersipCashier\\MembershipCashierW\\Controllers\\ControllerBase\\WebApiControllerBase.cs:line 64"
}

**Comment by yhurynovich** [comment]
This happens when your session expires. You need to be logged in

**Comment by yhurynovich** [comment]
fixed
