### ISSUE TITLE
No API to add product to Client

### ISSUE THREAD

**Issue by valpetruk** [yhurynovich/MembersipCashier#5]
It doesn't seem like there is an API to add assign product to a client from Modal window. seems like that /api/Product supposed to adds new Product. Couldn't make it work return success but no content.
![image](https://user-images.githubusercontent.com/29589089/30464635-a87795a4-99a0-11e7-88cf-0d44a6ab2a9e.png)

![image](https://user-images.githubusercontent.com/29589089/30464660-d7d0faa2-99a0-11e7-851e-bad2974ff03e.png)

**Comment by yhurynovich** [comment]
ProductController:PUT

**Comment by yhurynovich** [comment]
You need to use Product:GET to find product and then somehow join with the products from ClientLastUsedProducts
